import {
  LayoutDashboard,
  ClipboardList,
  ShoppingCart,
  Users,
  Car,
  Bike,
  Package,
  UserSquare2,
  BarChart3,
  Settings,
  Plus,
  Trash2,
  Search,
  ChevronUp,
  ChevronDown,
  LogOut,
  Bell,
  CheckCircle2,
  Clock,
  AlertCircle,
  Wrench,
  Fuel,
  Printer,
  History,
  HardDrive,
  CreditCard,
  Banknote,
  Wallet,
  AlertTriangle,
  ArrowUp,
  ArrowDown,
  TrendingUp,
  Calendar,
  Phone,
  Eye,
  Pencil,
  User,
  Star,
  Boxes,
  ArrowLeftRight,
  ClipboardCheck,
  Lock,
  Tag,
  ScanBarcode,
  Send,
  RefreshCcw,
  QrCode,
  Check
} from "lucide-react";

export const Icons = {
  Barcode: ScanBarcode,
  Dashboard: LayoutDashboard,
  Antrean: ClipboardList,
  Kasir: ShoppingCart,
  Pelanggan: Users,
  KendaraanMobil: Car,
  KendaraanMotor: Bike,
  Inventory: Package,
  Karyawan: UserSquare2,
  Laporan: BarChart3,
  Settings: Settings,
  Plus: Plus,
  Delete: Trash2,
  Search: Search,
  ChevronUp: ChevronUp,
  ChevronDown: ChevronDown,
  Logout: LogOut,
  Notification: Bell,
  Success: CheckCircle2,
  Pending: Clock,
  Warning: AlertCircle,
  Repair: Wrench,
  Oil: Fuel,
  Print: Printer,
  History: History,
  Database: HardDrive,
  Card: CreditCard,
  Cash: Banknote,
  EWallet: Wallet,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  Chart: TrendingUp,
  Alert: AlertTriangle,
  Calendar: Calendar,
  Whatsapp: Phone,
  Eye: Eye,
  Edit: Pencil,
  User: User,
  Star: Star,
  Boxes: Boxes,
  StockInOut: ArrowLeftRight,
  StockOpname: ClipboardCheck,
  Lock: Lock,
  Tag: Tag,
  Clock: Clock,
  Send: Send,
  RefreshCcw: RefreshCcw,
  QrCode: QrCode,
  Check: Check
};
